version: "2"
services:
  db:
      image: mariadb
      ports:
        - "33066:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=12345
      volumes:
          - ./database/mariadb:/var/lib/mysql
  myadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db:db
      ports:
        - "7777:80"
  nginx:
      build:
          context: ./nginx
      links:
          - fpm
      ports:
          - "8080:80"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      ports:
          - "9000:9000"
      links:
          - db
  redis:
      image: redis
      ports:
        - "6666:6379"
