nginx:
  image: nginx:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php-fpm:fpm

php-fpm:
  build: .
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm/:/var/log/php-fpm/:rw
  links:
    - db:db
    - redis:redis

myadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db:db
      ports:
        - "7777:80"

db:
  image: mariadb:latest
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "123456"

redis:
  image: redis:latest
  ports:
    - "6379:6379"

mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - ./mongo:/data/db
  environment:
    - MONGODB_USERNAME=root
    - MONGODB_PASSWORD=123456

mongo-express:
  image: mongo-express
  ports:
  - "8081:8081"
  links:
  - mongo:mongo
  environment:
    - ME_CONFIG_BASICAUTH_USERNAME=root
    - ME_CONFIG_BASICAUTH_PASSWORD=123456
