version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "8080:80"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=docker"
  db:
      image: mariadb
      ports:
        - "33066:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=12345
          - MYSQL_DATABASE=docker
      volumes:
          - ./database/mariadb:/var/lib/mysql
  myadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db:db
      ports:
        - "7777:80"
  redis:
      image: redis
      ports:
        - "6666:6379"
